# Generated by Django 4.2.8 on 2023-12-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10)),
                ('standard', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('admission', models.CharField(max_length=10)),
                ('session', models.CharField(choices=[('2023-2023', '2023-2024'), ('2023-2024', '2023-2025'), ('2023-2025', '2023-2026')], max_length=10)),
            ],
        ),
    ]
